variable "project" {}
variable "network_name" {}
variable "routing_mode" {}
variable "project_id" {}
variable "description" {}
variable "shared_vpc_host" {}
variable "delete_default_internet_gateway_routes" {}
variable "mtu" {}
variable "company" {}
variable "env" {}
variable "auto_create_subnetworks" {}
variable "region" {}
variable "pub_subnet_cidr" {}
variable "pri_subnet_cidr" {}
