variable "project" {}
variable "network_name" {}
variable "routing_mode" {}
variable "project_id" {}
variable "description" {}
variable "mtu" {}
variable "company" {}
variable "env" {}
variable "region" {}
variable "pri_subnet_cidr" {}
variable "pri_vpc_peering_address" {}
