variable "project" {}
variable "region" {}
variable "env" {}
variable "company" {}
variable "network_name" {}
variable "routing_mode" {}
variable "description" {}
variable "mtu" {}
variable "zone" {}
variable "pri_subnet_cidr" {}
variable "pri_vpc_peering_address" {}
variable "gke_cluster_ipv4_cidr" {}