variable "project" {}
variable "region" {}
variable "env" {}
variable "company" {}
variable "network_name" {}
variable "auto_create_subnetworks" {}
variable "routing_mode" {}
variable "description" {}
variable "shared_vpc_host" {}
variable "delete_default_internet_gateway_routes" {}
variable "mtu" {}
variable "gcp_credentials_file" {}
variable "zone" {}
variable "pub_subnet_cidr" {}
variable "pri_subnet_cidr" {}
variable "office_ip" {}
variable "failsafe_ip" {}